import type { NextPage } from 'next'
import Head from 'next/head'
import {
  ChakraProvider,
  useColorModeValue
} from '@chakra-ui/react'

import { AppHeader } from '../components/AppHeader'
import { AppMain } from '../components/AppMain'

const Home: NextPage = () => {
  return (
    <ChakraProvider>
      <App />
    </ChakraProvider>
  )
}

export default Home

function App(){
  const bg = useColorModeValue('#fafafa86', '#434343')

  return (
    <div style={{
      backgroundColor: bg,
      minHeight: '100vh'
    }}>
      <Head>
        <title>Calculadora</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AppHeader />
      
      <AppMain />
    </div>
  )
}